### ISSUE TITLE
No more accents in Greek

### ISSUE THREAD

**Issue by chrisauf** [flathub/com.viber.Viber#10]
Since yesterday, after re-installing Viber via flatpak in a terminal, I cannot use the accents and other diacritics in Viber when I write in Greek. 
No other program is affected, I can use these characters as always in  Thunderbird, Open Office Writer, Skype, Signal  and even here.
How can I get back my diacritics in Viber?

**Comment by johnr1** [comment]
Can confirm. I also have the issue.

**Comment by chrisauf** [comment]
I solved the problem by uninstalling completely Viber first, then re-installing it via the following procedure in a terminal:
1.-   sudo apt install alien
2.-   wget https://download.cdn.viber.com/desktop/Linux/viber.rpm
3.-   sudo alien --to-deb --scripts viber.rpm
4.-   sudo dpkg -i viber_xxxx_amd64.deb
This downloads the latest version of Viber in .rpm, transforms it into .deb and then installs it.
Everything works fine for me now under Ubuntu 18.04 LTS

**Comment by johnr1** [comment]
Hey, thanks a lot. I will use the workaround on my ubuntu installs. I managed to get it to work on Arch with the AUR package as well, but I was hoping to be able to use flatpak version.

**Comment by chrisauf** [comment]
Parakalo! 
I suppose that flatpak is fine for  languages that use the latin alphabet, but Greek has many particularities that do not exist in other languages. This must explain that.

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
