### ISSUE TITLE
Viber can not run after update

### ISSUE THREAD

**Issue by ivonenchev** [flathub/com.viber.Viber#12]
After update, when I have tried to run the Viber, with command flatpak run com.viber.Viber receive an error with folloling text : 

QFactoryLoader::QFactoryLoader() checking directory path "/app/extra/viber/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/com.viber.Viber/commit/b8275680fe1cd87132b30346778a0b5a9595cf9a
