### ISSUE TITLE
can't start viber

### ISSUE THREAD

**Issue by user216** [flathub/com.viber.Viber#13]
endless os

can't start viber

~$ flatpak run com.viber.Viber
Qt: Session management error: None of the authentication protocols specified are supported
sh: xdg-mime: command not found
~$

**Comment by andriy-f** [comment]
I get similar issue on OpenSuse 15.1

```
flatpak run com.viber.Viber
sh: xdg-mime: command not found
```

also if I run desktop shortcut command from Terminal:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=viber com.viber.Viber
sh: xdg-mime: command not found
```

But if I run shortcut directly from KDE, it launches

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.

**Comment by karama300** [comment]
I can confirm the problem appears with Fedora 37.
