### ISSUE TITLE
Viber Out doesn't work

### ISSUE THREAD

**Issue by pizzadude** [flathub/com.viber.Viber#14]
Viber Out (requires credits) doesn't work in the flatpak. It just "rings" forever with every phone number tested. With the regular deb version (even sandboxed with firejail) it works fine.

**Comment by alexkoster** [comment]
Same issue here on Fedora 30 Beta - I noticed i can see the microphone level moving in the Tools>Modify Audio Video box, but I'm unable to see any webcam preview (though it appears to detect my webcam).  Again, same problem as @pizzadude mentioned - trying Viber Out calling for audio or video rings forever using the flatpak version from flathub, but installing the .rpm version from https://www.viber.com/download/ works as intended.

**Comment by sagarchalise** [comment]
Actually, not just viber out but free call also doesn't work in flathub version. It rings in my side but the destination is unaware of the call.

**Comment by alex-theoto** [comment]
Is there any update about this problem?

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
