### ISSUE TITLE
Missing menu minimize/maximaze/close under wayland

### ISSUE THREAD

**Issue by ivonenchev** [flathub/com.viber.Viber#15]
I have an issue with viber from flathub Issue is that under wayland I cannot see menu for minimize/maximaze/close.

My operation system is OpenSuse Tumbleweed. 

How can I fix it.

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
