### ISSUE TITLE
Unusable on Debian 10

### ISSUE THREAD

**Issue by GogoAkira** [flathub/com.viber.Viber#16]
No resize icon, unable to resize.  Had to change resolution to 1200 4:3 just to be able to click the button to add phone number.  After it connected still unusable, not able to resize, app is bigger than my 1080 screen, twice.

Everyone else has the same issues as they commented on flathub debian store comments.

Please add resize ability to app.

**Comment by sagarlf** [comment]
If I am getting the issue right, this is an resolution issue. I am using **--env=QT_AUTO_SCREEN_SCALE_FACTOR=0** with viber run command.
May be give it a try.

**Comment by GogoAkira** [comment]
Oh thanks I will try viber again, I had the same problem with VLC and found that solution to put that text into file /etc/environment and it works, gonna try viber now.

thanks for reminding me
