### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by vertigo77** [flathub/com.viber.Viber#17]
Just tried installing today:

> error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

Seems the deb file changed. Is there a way to continue a proper flatpak installation when this happens again?

**Comment by Paul-Stern** [comment]
This is once again an issue. Please check this out again.

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.

**Comment by ffoxD** [comment]
Currently experiencing this issue. 

error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by kaungsettnaing-llops** [comment]
I'm also experiencing this issue as well.
Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by itsanov** [comment]
Same for Fedora 39

**Comment by crush2000** [comment]
Same problem on Zorin 17 Pro based on Ubuntu 22.04. Need some quick fix.

**Comment by AnoKaJIunCuC** [comment]
The same problem on Alt Linux

**Comment by Anastopoulos** [comment]
I am also having the same issue on Ubuntu 23.10.

**Comment by OlegShchavelev** [comment]
Hello. Unfortunately, it is not possible to install Viber using Flatpak tools. An error occurs during the installation process:

```shell
Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
```
Personally, I use ALT Regular Gnome

```shell
distro_info v20230406 (EPM version 3.60.5-alt1) : Copyright � 2007-2023 Etersoft

                       Pretty name (--pretty): ALT Regular (20240122) (Sisyphus)
           (--distro-name / --distro-version): Sisyphus / 20240122 (orig. Sisyphus 20240112)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): kvm
                        CPU Cores/MHz (-c/-z): 16 / 2899 MHz
                      System memory size (-m): 3919 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/


```
I am using the flatpak version 1.14.5. Please tell me if you need to issue a new problem?

**Comment by mozo78** [comment]
With Fplatpak 1.1.15 the problem is still here. I can't install Viber:
```
Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
```
