### ISSUE TITLE
Camera does not work

### ISSUE THREAD

**Issue by frpenguin** [flathub/com.viber.Viber#21]
I am on Manjaro using the Flatpak version. Video does not work.

This is my output:

`flatpak -v run com.viber.Viber
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Cleaning up unused container id 1314539307
F: Allocated instance id 3818626767
F: Add defaults in dir /com/viber/Viber/
F: Add locks in dir /com/viber/Viber/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/user/.config/pulse/client.conf': Error opening file /home/user/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 32 xdg-dbus-proxy --args=34'
F: Running 'bwrap --args 32 viber'
Qt: Session management error: None of the authentication protocols specified are supported
sh: xdg-mime: command not found
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
qrc:/QML/DebugMenu.qml:262: TypeError: Cannot call method 'isWasabiEnabled' of undefined
qrc:/QML/DebugMenu.qml:289: TypeError: Cannot call method 'isSearchInCommunitiesForceEnabled' of undefined
qrc:/QML/DebugMenu.qml:296: TypeError: Cannot call method 'isOOABURISpamCheckerForceEnabled' of undefined
qrc:/QML/DebugMenu.qml:304: TypeError: Cannot call method 'isRateCallQualityForceEnabled' of undefined
qml: Uncaught (in promise) #<OverconstrainedError>
`

The part:
`qml: Uncaught (in promise) #<OverconstrainedError>`
appears when I select the "Audio & Video" Section in Settings

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
