### ISSUE TITLE
Share screen functionality does not work

### ISSUE THREAD

**Issue by pbetsinski** [flathub/com.viber.Viber#22]
Sharing a screen during call does not work on both Kubuntu 19.10 and Kubuntu 20.04. Clicking on the "Share screen" button minimizes the application like it should, but doesn't create a video stream.

**Steps to reproduce:**
1. flatpak install com.viber.Viber
2. flatpak -v run com.viber.Viber
3. Complete the first time setup (phone verification, etc)
4. Make a call and attempt to share the screen

**Actual results:**
Application minimizes, but video stream doesn't start.
Error is thrown in the log:
`qml: 21.193 JS: beginBrowserSelfVideoStreamRestart(streamActive = 1, streamType = 1, fromVoiceLib = 0)
qml: 21.193 JS: n_tracks = 0, streamActiveEqual = false, streamTypeEqual = false
qml: 21.194 JS: restartSelfVideoStream_() with selfVideoActive = 1, selfVideoType = 1
qml: 21.194 JS: Recreating stream
qml: 21.195 JS: beginBrowserSelfVideoStreamRestart: restartSelfVideoStream_() failed with error: NotReadableError: Could not start video source`

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
