### ISSUE TITLE
Version 13.2.0.8 replaces the Greek char 'Σ" with latin 'C' on contact names

### ISSUE THREAD

**Issue by kostas-gr** [flathub/com.viber.Viber#23]
Latest Viber update, wrongly replaces the Greek char 'Σ' with the latn 'C';only the capital letters.

i.e. The Name ΚΩΣΤΑΣ is displayed as ΚΩCΤΑC

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
