### ISSUE TITLE
Wrong sorting of stacks of messages

### ISSUE THREAD

**Issue by aacharya420** [flathub/com.viber.Viber#28]
I changed the system date of device, increased it by 3 days .I had a conversation with friend (let A).Then i changed the date to actual date...Again i had conversation with a friend B and after i didn't have conversation with A again. But the  display order of messages is not correct. Actually recent message i.e. conversation with B should be displayed first. But conversation with A is is in first place of stack ..The correct order of message blocks should have been first B then A. .So i guess its an error.

**Comment by akurtakov** [comment]
Do you still see the issue with latest updates?

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.
