### ISSUE TITLE
Bug? Exiting Viber not works!

### ISSUE THREAD

**Issue by vivazkote** [flathub/com.viber.Viber#29]
Hello!
I did 'Exit Viber' from it's settings.
But shortly after Viber again recieved call.

**Comment by vivazkote** [comment]
well, after doing Exit from menu settings>general>exit, I am also stoping Viber with app's 'Force stop' function. This works.
But why should we do more job?? Just correct functional, Viber developers! Please.

**Comment by akurtakov** [comment]
Do you still face the issue with latest version?

**Comment by vivazkote** [comment]
Yes, issue is still here. V17.4.0.4

**Comment by akurtakov** [comment]
I've just built v18.2.0.2, should come to you tomorrow. Would you please check whether the problem fixes for you?

**Comment by akurtakov** [comment]
There is new version of Viber on latest 23.08 freedesktop runtime. Please update and let us know if it still fails for you?

**Comment by vivazkote** [comment]
just retested, problem exists. Fresh install, Viber v20.9.2.0 on Android 12, Tab S6

**Comment by vivazkote** [comment]
also checked on phones with Android 8 & 13

**Comment by akurtakov** [comment]
I don't think one can even use flatpaks on Android devices. My test is on Fedora 39 but even this is irrelevant as Flatpak's runtime org.freedesktop.Platform 23.08 provides all needed libs. If you haven't installed via flatpak you opened your issue in the wrong place to start with.

**Comment by akurtakov** [comment]
As this bug seems to be misreported here I'm closing it . If you have problems running Viber on Linux via Flatpak please reopen with details.
