### ISSUE TITLE
Can't login to Viber using QR Code.

### ISSUE THREAD

**Issue by PranavBhattarai** [flathub/com.viber.Viber#31]
I tried scanning multiple times, but no matter what, it doesn't log me into my Viber account.
![Screenshot from 2021-07-07 09-41-25](https://user-images.githubusercontent.com/32763112/124698377-77593700-df08-11eb-87bf-7512ae3c1c70.png)

What to do!?
And **who** maintains this Viber? Is this an official Viber or something else?!

**Comment by akurtakov** [comment]
Do you still see the issue?
It's not official Viber, it's repackaged native build from viber.com for easier installability. As there are no code changes I expect you'll be facing same issues if installing rpm/deb package.

**Comment by PranavBhattarai** [comment]
@akurtakov 
> Do you still see the issue?
I don't use Viber these days. I wanted it for a while but was never impressed by the software features both on Android and on Desktop.

And comparing Viber with Telegram "feature-wise" will be like comparing an aircraft with a rocket. 
You can close this issue if you want.
