### ISSUE TITLE
cannot install viber 

### ISSUE THREAD

**Issue by ivonenchev** [flathub/com.viber.Viber#34]
Fedora 34, cannnot install viber. Output : 

flatpak install flathub -y --user com.viber.Viber
Looking for matches…

com.viber.Viber permissions:
    ipc                   network       pulseaudio      wayland      x11      devices      file access [1]
    dbus access [2]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-pictures, xdg-videos, ~/.ViberPC:create
    [2] org.freedesktop.Notifications, org.kde.StatusNotifierWatcher

        ID                      Branch         Op         Remote          Download
 1. [✗] com.viber.Viber         stable         i          flathub         110,1 MB / 111,5 MB

Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by wooque** [comment]
New version (16.1.0.37) is out, maintainers have to update this flatpak

**Comment by ma3yta** [comment]
woks fine now. please check
