### ISSUE TITLE
Cannot reinstall after broken update.

### ISSUE THREAD

**Issue by baskinsy** [flathub/com.viber.Viber#40]
Hello,

I had a power loss when during flatpak update. The only package that was updating at that time was Viber. After that I am unable to install it with the following error:

```
Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.viber.Viber: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

I have tried cleaning any occurrence of viber files I can find and don't know where else to look. Any hints on how to install it again?

Thank you.

**Comment by ma3yta** [comment]
@baskinsy woks fine now. please check

**Comment by baskinsy** [comment]
I can confirm it works now! Thanks for the fix!
