### ISSUE TITLE
Nos slell-check, no "follow the system" for light/dark option

### ISSUE THREAD

**Issue by MindlessDreams** [flathub/com.viber.Viber#45]
Hello, is it possible to activate the spell-check and the "follow the system" for light/dark option? Thank you for maintaining Viber flatpak!

**Comment by akurtakov** [comment]
Would you please share links explaining how to enable to these viber application options? Or maybe I'm not understanding your request.

**Comment by akurtakov** [comment]
Closing due to lack of response from reporter.

**Comment by MindlessDreams** [comment]
Hello, I am sorry for the late response. This is what I am talking about - a screenshot from viber on windows - it has a toggle - follow system theme. Thank you!
![viber auto theme](https://user-images.githubusercontent.com/103588255/184660162-b7dec764-a811-4cc9-bea6-0ae0f57dbbc5.jpg)
