### ISSUE TITLE
After 28 April 2022 update, Viber does not run.

### ISSUE THREAD

**Issue by jivko-chobanov** [flathub/com.viber.Viber#46]
I use flatpak 1.2.5 on Debian 9 (Stretch).

After the update on 28 April 2022:
    Sdk: org.freedesktop.Sdk/x86_64/21.08                                                                                                                                                                       
    Commit: c47accc1531978ace83e2ec9147154e286c937b12d57602896e790f71abef01b                                                                                                                                       
    Parent: 587a3af5930847519a2981c6f8c3b79864b9ef08086709b1322868af325f5e58                                                                                                                                       
   Subject: Update to 21.08 runtimes (886e43ea)                                                                                                                                                                    
      Date: 2022-04-28 08:23:23 +0000

when I do:
flatpak run -d com.viber.Viber

I get:
error: runtime/org.freedesktop.Sdk/x86_64/21.08 not installed

when:
flatpak install flathub runtime/org.freedesktop.Sdk/x86_64/21.08
I get successful installation of freedesktop.Sdk then again I cannot run Viber even after reinstalling Viber.

when:
flatpak run -d com.viber.Viber
Then it gives me no further errors, but does not run, nothing happens, console lets me type a new command.

when:
flatpak run -v com.viber.Viber

I get:
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/j/.local/share/flatpak
F: Opening user flatpak installation at path /home/j/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/j/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/j/.var/app/com.viber.Viber/.ld.so/1a4ad2177306ae5c6e972ee580afa9eec261eb092edf25644ec97390c825c8e3
F: Running: 'bwrap --args 21 ldconfig -X -C /run/ld-so-cache-dir/1a4ad2177306ae5c6e972ee580afa9eec261eb092edf25644ec97390c825c8e3'
F: Cleaning up unused container id 1238990630
F: Allocated instance id 3902520882
F: Add defaults in dir /com/viber/Viber/
F: Add locks in dir /com/viber/Viber/
F: Xdg dir xdg-documents is $HOME (i.e. disabled), ignoring
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 36 xdg-dbus-proxy --args=38'
F: Running 'bwrap --args 36 viber'

**Comment by akurtakov** [comment]
Is org.freedesktop.Platform 21.08 installed?

**Comment by jivko-chobanov** [comment]
It seems to be installed. I don't know how to check properly. When:
flatpak -v update com.viber.Viber

Then:
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/j/.local/share/flatpak
Looking for updates…
F: Fetching summary file for remote ‘flathub’
F: Transaction: update flathub:app/com.viber.Viber/x86_64/stable[$old]
F: Updating remote metadata for flathub
F: marking op update:app/com.viber.Viber/x86_64/stable resolved to c47accc1531978ace83e2ec9147154e286c937b12d57602896e790f71abef01b
F: Updating dependent runtime runtime/org.freedesktop.Platform/x86_64/21.08
F: Transaction: update flathub:runtime/org.freedesktop.Platform/x86_64/21.08[$old]
F: marking op update:runtime/org.freedesktop.Platform/x86_64/21.08 resolved to e5aff027f1cfc1b950d476dab5159628f077a4ca114e87160a123df9cce700bf
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/21.08[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/21.08[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.openh264/x86_64/2.0[*]
F: marking op install/update:runtime/org.freedesktop.Platform.openh264/x86_64/2.0 resolved to 73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
F: marking op install/update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/21.08 resolved to e9c82ce5bfa88203e332b249c865f4e75e41316fa4b319e74ceb04e4939d629a
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/21.08 resolved to 9a9759c24a006b7482cacade4e0ef03895f49fb575ad76b578e7f18a32d39cda
F: marking op install/update:runtime/org.freedesktop.Platform.GL.default/x86_64/21.08 resolved to ccbb8e3946891ef9f43e7503ec6a7d38ddd589b8adda4b8597b0db2deb78a520
Nothing to do.

**Comment by akurtakov** [comment]
It just occured to me that flatpak 1.2.5 is quite old (https://github.com/flatpak/flatpak/releases/tag/1.2.5).
On my Fedora 36 machine:
```
flatpak --version
Flatpak 1.12.7
```
Is there a chance you can get newer flatpak installed on your machine?

**Comment by akurtakov** [comment]
Also do you have it user or system installed?

**Comment by jivko-chobanov** [comment]
On Debian 9 (Stretch) it is the newest possible version of flatpak via backports - [https://packages.debian.org/search?keywords=flatpak](https://packages.debian.org/search?keywords=flatpak) 

I installed it with "sudo apt-get install flatpak", so I guess it's a system install.

**Comment by akurtakov** [comment]
This sounds related to https://github.com/flatpak/flatpak/issues/4724 . Can you try the suggestions from it?

**Comment by jivko-chobanov** [comment]
It's not useful for my case. I've never used the --user option, everything is system-wide.
When:
flatpak remotes

Then:
Name    Options 
flathub   system
winepak system

**Comment by akurtakov** [comment]
Would you please post the output of `flatpak list`?

**Comment by jivko-chobanov** [comment]
`flatpak list`

Description - Application - Version - Branch - Arch - Origin - Installation

Transmission - Download and share files over BitTorrent                                                                                com.transmissionbt.Transmission  3.00     stable x86_64 flathub system

Viber - We connect people, no matter who they are or where they are from.                                                              com.viber.Viber                  11.9     stable x86_64 flathub system

XnView MP - View and organize your images                                                                                              com.xnview.XnViewMP              0.99.7   stable x86_64 flathub system

FileZilla - FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intu… org.filezillaproject.Filezilla   3.59.0   stable x86_64 flathub system

Freedesktop Platform - Shared libraries                                                                                                org.freedesktop.Platform         21.08.13 21.08  x86_64 flathub system

Mesa - Mesa - The 3D Graphics Library                                                                                                  …freedesktop.Platform.GL.default 21.3.8   21.08  x86_64 flathub system

Intel       …reedesktop.Platform.VAAPI.Intel          21.08  x86_64 flathub system

openh264 - OpenH264 Video Codec provided by Cisco Systems, Inc.                                                                        …g.freedesktop.Platform.openh264 2.1.0    2.0    x86_64 flathub system

Freedesktop SDK - Tools and headers for developing applications                                                                        org.freedesktop.Sdk              21.08.13 21.08  x86_64 flathub system

GNOME Application Platform version 41 - Shared libraries used by GNOME applications                                                    org.gnome.Platform                        41     x86_64 flathub system

**Comment by akurtakov** [comment]
Would you please provide the output of `journalctl -e` after running viber ?

**Comment by jivko-chobanov** [comment]
`journalctl -e`
May 04 21:24:21 zhivko polkitd(authority=local)[1457]: Registered Authentication Agent for unix-process:32691:4142055 (system bus name :1.91 [flatpak run -v com.viber.Viber], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)

May 04 21:24:21 zhivko systemd[2834]: Started flatpak-com.viber.Viber-32691.scope.

May 04 21:24:21 zhivko polkitd(authority=local)[1457]: Unregistered Authentication Agent for unix-process:32691:4142055 (system bus name :1.91, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8) (disconnected from bus)

May 04 21:24:25 zhivko sudo[32716]:        j : TTY=pts/7 ; PWD=/home/j ; USER=root ; COMMAND=/bin/journalctl -e

**Comment by akurtakov** [comment]
I just got confirmation that it installs and runs fine on Debian 11. Considering that Debian 9 has just a month more of support (if I read things right) have you considered updating to newer version?

**Comment by jivko-chobanov** [comment]
Yes, probably that will solve it. It's just that a big chunk of the promise of flatpak and snap packages is that you can run them in an old or weird linux operating system and they will run just fine, because they are in self-sufficient containers. It seems that the issue of updatability is moved from the package itself to the updatability and installation requirements of flatpak/snap system that supports the packages.

**Comment by akurtakov** [comment]
You are correct. It's just impossible to stay compatible forever as that would mean no changes are allowed in the flatpak system itself. It's an issue that it allows updating to runtime that would not be able to execute after that, in such cases it should just stay on the old version and notify the user about this "uninstallable" update.

**Comment by akurtakov** [comment]
Btw, if you have time would you please try installing Atom from flathub? I wonder whether the same issue happens.

**Comment by jivko-chobanov** [comment]
`app/io.atom.Atom/x86_64/stable` runs fine, but it requires 20.08, not 21.08 of freedesktop
```
 1. [✓] org.freedesktop.Sdk                             x86_64            20.08             flathub                                                                                 
 2. [✓] org.freedesktop.Platform.GL.default             x86_64            20.08             flathub                                                                                
 3. [✓] org.freedesktop.Sdk.Locale                      x86_64            20.08             flathub                                                                                 
 4. [✓] org.freedesktop.Platform.VAAPI.Intel            x86_64            20.08             flathub                                                                                   
 5. [✗] io.atom.Atom                                    x86_64            stable            flathub
 ```

**Comment by akurtakov** [comment]
Last try - when viber is not run, remove ~/.var/app/com.viber.Viber/cache and start again. That folder is quite suspicious - qt, mesa, fontconfig - things that could easily break things on runtime version change.

**Comment by jivko-chobanov** [comment]
Didn't work. Thank you for your support. :)

**Comment by akurtakov** [comment]
Marking as wontfix. Debian 11 (current stable) works just fine and Debian 9 has roughly 2 months of support upstream so won't spend more time on it.
