### ISSUE TITLE
[Update August 12] Viber does not open

### ISSUE THREAD

**Issue by itsnotsaved** [flathub/com.viber.Viber#54]
System: Ubuntu 22.04.01 | x11 | gnome 42.04
Kvantum manager: 1.0.4

flatpak run com.viber.Viber
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
sh: line 1: xdg-mime: command not found
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  allow-loopback-in-peer-connection  
  *  application-name ViberPC 
  *  autoplay-policy no-user-gesture-required 
  *  browser-subprocess-path /app/extra/viber/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture,AudioServiceOutOfProcess 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess,NetworkServiceInProcess 
  *  enable-threaded-compositing  
  *  enable-usermedia-screen-capture  
  *  in-process-gpu  
  *  use-gl desktop 

QQmlApplicationEngine failed to load component
qrc:/Resources/QML/MainWindow.qml: module "kvantum" is not installed
qt.core.qobject.connect: QObject::connect(QWindow, ApplicationEngine): invalid nullptr parameter

**Comment by itsnotsaved** [comment]
And, https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb doesn't open too. (it can install well without problem)

**Comment by kalligator** [comment]
I believe the workaround I suggested on #53 should work for you guys as well

**Comment by akurtakov** [comment]
There is new version of Viber on latest 23.08 freedesktop runtime. Please update and let us know if it still fails for you?

**Comment by akurtakov** [comment]
Closing as there have been a lot of changes in the last year and thus outdated.

**Comment by itsnotsaved** [comment]
Ubuntu 22.04.3 | x11
Viber 20.3.0.1

![image](https://github.com/flathub/com.viber.Viber/assets/73447325/c7c78c7e-6b98-45f6-843c-71148a4cf7eb)

**Comment by itsnotsaved** [comment]
https://github.com/flathub/com.viber.Viber/issues/74
