### ISSUE TITLE
Viber dark mode with the system

### ISSUE THREAD

**Issue by MindlessDreams** [flathub/com.viber.Viber#56]
Hello, is it possible to get the Flatpak version of viber to follow the system light/dark mode. Windows version has this toggle in menus. Thank you!
![184660162-b7dec764-a811-4cc9-bea6-0ae0f57dbbc5](https://user-images.githubusercontent.com/103588255/191924463-4bd674ae-0623-4698-ab5f-e4011e06bda6.jpg)

**Comment by akurtakov** [comment]
This feature is missing from Viber on Linux so you would have to ask on https://help.viber.com for it. If/when it comes to Linux version of Viber (deb/rpm) let us know and we will update the flatpak. Until then there is nothing to be done from our side as this is purely application internals.
