### ISSUE TITLE
Cannot run Viber on Opensuse Tumbleweed

### ISSUE THREAD

**Issue by ivonenchev** [flathub/com.viber.Viber#60]
When I try to run the Viber from the terminal, I face the following text : 

flatpak run com.viber.Viber                                                                                                      ─╯
Qt: Session management error: None of the authentication protocols specified are supported
sh: ред 1: xdg-mime: command not found
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  allow-loopback-in-peer-connection  
  *  application-name ViberPC 
  *  autoplay-policy no-user-gesture-required 
  *  browser-subprocess-path /app/extra/viber/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture,AudioServiceOutOfProcess 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess,NetworkServiceInProcess 
  *  enable-threaded-compositing  
  *  enable-usermedia-screen-capture  
  *  in-process-gpu  
  *  use-gl desktop 

[2:18:0215/125346.757060:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket:  This address has already in used (98)
xkbcommon: ERROR: Couldn't process include statement for 'us(phonetic)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[2:16:0215/125346.805239:FATAL:xkb_keyboard_layout_engine.cc(640)] Keymap file failed to load: us-phonetic

**Comment by ivonenchev** [comment]
I am using Nvidia driver and xOrg graphic server

**Comment by acim** [comment]
I have the same problem:

```
Qt: Session management error: None of the authentication protocols specified are supported
sh: line 1: xdg-mime: command not found
qt.webenginecontext: 

GLImplementation: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
Using Default SG Backend: yes
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  allow-loopback-in-peer-connection  
  *  application-name ViberPC 
  *  autoplay-policy no-user-gesture-required 
  *  browser-subprocess-path /app/extra/viber/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture,AudioServiceOutOfProcess 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess,NetworkServiceInProcess 
  *  enable-threaded-compositing  
  *  enable-usermedia-screen-capture  
  *  in-process-gpu  
  *  use-gl desktop 

[2:34:0317/231549.745022:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
xkbcommon: ERROR: Couldn't process include statement for 'de(latin)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[2:31:0317/231549.748385:FATAL:xkb_keyboard_layout_engine.cc(640)] Keymap file failed to load: de-latin
```
I tried #53 but it didn't help.

**Comment by temmiq** [comment]
I have the same problem, installed flatpack, maybe someone has how to solve this problem

**Comment by temmiq** [comment]
strangely switched to the Russian keyboard, and it worked, thanks for the hint

**Comment by akurtakov** [comment]
I'm closing this one as I don't see anything that can be done from flatpak side. Hopefully this is fixed in latest update. If someone thinks there is a fix that can be done from flatpak side please provide a PR.
