### ISSUE TITLE
Publish new version (20.3.0.1) on Flathub

### ISSUE THREAD

**Issue by xalt7x** [flathub/com.viber.Viber#65]
Version 20.3.0.1 was merged with #62  but Flathub still provides 18.2.0.2.
Updated version fixes [bug with a tray icon menu](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/375) on GNOME and possibly other Desktop Environments.
P.S. Other relevant issue - #4

**Comment by akurtakov** [comment]
Done via https://buildbot.flathub.org/#/builders/2/builds/21717
