### ISSUE TITLE
libsframe needs to be copied when updating to runtime 23.08

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.viber.Viber#68]
Hi, this is a heads up.

`ar` since binutils >=2.40 links against libsframe but binutils is entirely in the SDK and not in platform runtime. So `libsframe` needs to be copied, else the `apply_extra` script won't work.

```
cp -a /usr/lib/$(gcc --print-multiarch)/libsframe.so* ${FLATPAK_DEST}/lib
```

Another option is to use bsdtar instead of ar.

Thanks

**Comment by akurtakov** [comment]
Have you reported this to flatpak runtime? It soulnd's like an issue ther.

**Comment by bbhtt** [comment]
Yes, talked with them. binutils won't be moved to the runtime, as they want to keep it light.

As apps are already copying libbfd-*.so and ar, it is assumed they should copy the other libraries too.

**Comment by bbhtt** [comment]
Re. https://github.com/akurtakov/com.viber.Viber/commit/0214556d40c78f80913ede131de471e8d111f112

You can remove `"ARCH_TRIPLE=$(gcc --print-multiarch) && cp /usr/lib/${ARCH_TRIPLE}/libbfd-*.so /app/lib"`, this was only needed by `ar` copied above.

**Comment by akurtakov** [comment]
Moved to bsdtar via https://github.com/flathub/com.viber.Viber/pull/71
