### ISSUE TITLE
Failed to find shared lib

### ISSUE THREAD

**Issue by vsraptor** [flathub/com.viber.Viber#70]
Flatpak version
1.12.7

```
#/var/lib/flatpak/exports/bin# /var/lib/flatpak/exports/bin/com.viber.Viber

/app/extra/viber/Viber: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory

/var/lib/flatpak/exports/bin# ldconfig -p | grep libevent
libevent_pthreads-2.1.so.7 (libc6,x86-64) => /lib/x86_64-linux-gnu/libevent_pthreads-2.1.so.7
libevent_openssl-2.1.so.7 (libc6,x86-64) => /lib/x86_64-linux-gnu/libevent_openssl-2.1.so.7
libevent_extra-2.1.so.7 (libc6,x86-64) => /lib/x86_64-linux-gnu/libevent_extra-2.1.so.7
libevent_core-2.1.so.7 (libc6,x86-64) => /lib/x86_64-linux-gnu/libevent_core-2.1.so.7
libevent-2.1.so.7 (libc6,x86-64) => /lib/x86_64-linux-gnu/libevent-2.1.so.7

#flatpak run com.viber.Viber
/app/extra/viber/Viber: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory
```

**Comment by andersrh** [comment]
I'm getting the same error. tested on two machines

**Comment by akurtakov** [comment]
Should be fixed by https://github.com/flathub/com.viber.Viber/pull/71

**Comment by vsraptor** [comment]
flatpak install --user https://dl.flathub.org/build-repo/51489/com.viber.Viber.flatpakref

seems to install new flatpak and viber in different place ... how can i find it.. or does it ?

under root : 

# flatpak run com.viber.Viber
qt.qpa.theme.dbus: Session DBus not running.
qt.qpa.theme.dbus: Application will not react to setting changes.
 Check your DBus installation.
sh: line 1: xdg-mime: command not found
[2:2:0926/091056.472694:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
root@vs:/# flatpak --version
Flatpak 1.12.7


under normal user still : 

$ flatpak run com.viber.Viber
/app/extra/viber/Viber: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory

**Comment by akurtakov** [comment]
just do `flatpak update` and your old flatpak should be updated to the new one.
