### ISSUE TITLE
Viber is not running since the day of 'flatpak update' on 07 October 2023.

### ISSUE THREAD

**Issue by alufd19** [flathub/com.viber.Viber#74]
OS: Arch Linux x86_64
Kernel: 6.1.57-1-lts
Flatpak version: Flatpak 1.15.4

flatpak run com.viber.Viber
Gtk-Message: 13:11:00.728: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:11:00.728: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
sh: line 1: xdg-mime: command not found
*** stack smashing detected ***: terminated

journalctl -e
                                                Module /app/extra/viber/lib/libpng16.so.16
                                                Module /app/extra/viber/lib/libjpeg.so.8 without build-id.
                                                Module /app/extra/viber/lib/libjpeg.so.8
                                                Module /app/extra/viber/lib/libicudata.so.66 without build-id.
                                                Module /app/extra/viber/lib/libicuuc.so.66 without build-id.
                                                Module /app/extra/viber/lib/libicuuc.so.66
                                                Module /app/extra/viber/lib/libXdamage.so.1 without build-id.
                                                Module /app/extra/viber/lib/libXcomposite.so.1 without build-id.
                                                Module /app/extra/viber/lib/libicui18n.so.66 without build-id.
                                                Module /app/extra/viber/lib/libicui18n.so.66
                                                Stack trace of thread 2:
                                                #0  0x00007fcf080a3e14 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x90e14)
                                                #1  0x00007fcf08051dce n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x3edce)
                                                #2  0x00007fcf0803983f n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2683f)
                                                #3  0x00007fcf0803a710 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x27710)
                                                #4  0x00007fcf08137fa9 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x124fa9)
                                                #5  0x00007fcf08139264 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x126264)
                                                #6  0x00007fcf0809d81d n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8a81d)
                                                #7  0x00007fcf0809dcbf n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8acbf)
                                                #8  0x00007fcee006997a n/a (/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.261 + 0x2c97a)
                                                #9  0x00007fcee006d7ac n/a (/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.261 + 0x307ac)
                                                #10 0x00007fcee006da65 n/a (/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.261 + 0x30a65)
                                                #11 0x00007fcee00728d6 n/a (/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.261 + 0x358d6)
                                                #12 0x00007fcee0077048 n/a (/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.261 + 0x3a048)
                                                #13 0x00007fcee00cead9 n/a (/usr/lib/x86_64-linux-gnu/libgstvulkan-1.0.so.0.2205.0 + >
                                                #14 0x00007fcee00d396c n/a (/usr/lib/x86_64-linux-gnu/libgstvulkan-1.0.so.0.2205.0 + >
                                                #15 0x00007fcee010bbaa n/a (/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvulkan.so +>
                                                #16 0x00007fcee5d1cbd8 n/a (/usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.2205.0 + >
                                                #17 0x00007fcee5d31416 n/a (/usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.2205.0 + >
                                                #18 0x00007fcef81ec63a n/a (/app/extra/viber/plugins/multimedia/libgstreamermediaplug>
                                                ELF object binary architecture: AMD x86-64

**Comment by itsnotsaved** [comment]
Works on Ubuntu 22.04.3 | x11
Viber 20.3.0.1
Flatpak 1.12.7

![image](https://github.com/flathub/com.viber.Viber/assets/73447325/c8566962-04c6-4438-9f96-3236c50277bc)
