### ISSUE TITLE
Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb (again)

### ISSUE THREAD

**Issue by FalxDraco** [flathub/com.viber.Viber#79]
Hello,

As per title.

Installation attempt:

```
flatpak install com.viber.Viber
Looking for matches…
Remotes found with refs similar to ‘com.viber.Viber’:

   1) ‘flathub’ (system)
   2) ‘flathub-user’ (user)

Which do you want to use (0 to abort)? [0-2]: 1

com.viber.Viber permissions:
    ipc      network      pulseaudio      wayland      x11      devices      file access [1]      dbus access [2]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-pictures, xdg-videos, ~/.ViberPC:create
    [2] org.freedesktop.PowerManagement, org.freedesktop.ScreenSaver, org.gnome.SessionManager, org.gtk.Notifications, org.kde.StatusNotifierWatcher


        ID                      Branch         Op         Remote          Download
 1. [✗] com.viber.Viber         stable         i          flathub         150.0 MB / 156.9 MB

Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

```

System:

```
flatpak --version
Flatpak 1.14.4
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic
```

**Comment by kaungsettnaing-llops** [comment]
Same issue.
Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by akurtakov** [comment]
I'm trying to update it but there seems to be much stricter flathub infrastructure which no longer accepts the hacky way viber is done. See https://github.com/flathub/com.viber.Viber/pulls for details . Any help is more than welcome as I'm kind of out of ideas and time for this .

**Comment by malimart** [comment]
I've found a workaround for the issue. After failing to install the flatpack I tried their AppImage which also did not work. I then managed to install and run Viber successfully by installing the .deb package via the terminal.

Download the Viber .deb package:
`wget -O ~/viber.deb https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb`

Install Viber using the downloaded package:
`sudo gdebi ~/viber.deb`

After completing these steps, Viber is available from the start menu.

**Comment by kaungsettnaing-llops** [comment]
@malimart Hey, I've tried your workaround. It didn't work for me. I'm using Pop_OS 22.04LTS. Yes, Viber can now be installed and is available in the start menu but it cannot run. 
What's working now for me is using the AppImage from the Viber download page. Give it executable permission and you can continue from there.

**Comment by Shished** [comment]
Why does flatpak downloads a deb package? Is it supposed do this?

**Comment by mozo78** [comment]
Same here:
`error: Failed to install com.viber.Viber: Wrong size for extra data`

**Comment by TingPing** [comment]
Fixed once new version is published.

10d022db571f4fcf7c447bcbce613d9413f9e3f4

**Comment by mozo78** [comment]
Flatpak new version or Viber new version?

**Comment by TingPing** [comment]
Just the flatpak, probably already live.

**Comment by mozo78** [comment]
Ah, I see, thanks :)

**Comment by 7system7** [comment]
The error reappeared again.

```
$ flatpak install viber  
Looking for matches…
Found ref ‘app/com.viber.Viber/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 

com.viber.Viber permissions:
    ipc      network      pulseaudio      wayland     x11     devices     file access [1]     dbus access [2]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-pictures, xdg-videos, ~/.ViberPC:create
    [2] org.freedesktop.PowerManagement, org.freedesktop.ScreenSaver, org.gnome.SessionManager, org.gtk.Notifications, org.kde.StatusNotifierWatcher


        ID                      Branch         Op         Remote          Download
 1. [✗] com.viber.Viber         stable         i          flathub         131,2 MB / 136,3 MB

error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
```

**Comment by fedorniakm** [comment]
Same here - the error happened again.

**Comment by endlessterror** [comment]
Please reopen this  issue. Platform details:
```

OS: Debian GNU/Linux 13 (trixie) x86_64
Host: AO756 (V2.21)
Kernel: Linux 6.12.73+deb13-amd64
Shell: bash 5.2.37
Display (CMO1113): 1366x768 @ 60 Hz in 12" [Built-in]
DE: KDE Plasma 6.3.6
WM: KWin (Wayland)
```

Update fails fromboth  discover and flatpak update. In synaptic error is "Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb".

Fromshell:

```
$ flatpak update com.viber.Viber
Looking for updates…


        ID                      Branch         Op         Remote          Download
 1. [✗] com.viber.Viber         stable         u          flathub         131,2 MB / 136,3 MB

Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
Updates complete.
error: There were one or more errors

```
