### ISSUE TITLE
Viber Aplication GUI got invisible after last update.

### ISSUE THREAD

**Issue by nikospantazis** [flathub/com.viber.Viber#9]
Viber Aplication GUI got invisible after last update. The application starts, the mouse cursor changes when passes over the application entries, everything inside the app window in invisible (white).

(On Debian buster)

flatpak --version
Flatpak 1.0.6

flatpak info com.viber.Viber
Ref: app/com.viber.Viber/x86_64/stable
ID: com.viber.Viber
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-20 20:26:47 +0000
Subject: Switch to stable runtime version 18.08 (79dccabe)
Commit: 7645126cc6fdba546d16d6d8b548d20d1b25a6f5e73e95d9fe7e278940a961e3
Parent: 0580aa5896873c18820ce4958c8ba98dfae47dbd949ff9d98f7cf0f3723629d2
Location: /var/lib/flatpak/app/com.viber.Viber/x86_64/stable/7645126cc6fdba546d16d6d8b548d20d1b25a6f5e73e95d9fe7e278940a961e3
Installed size: 40,3 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08

flatpak -v run com.viber.Viber
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/nikos/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nikos/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nikos/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3330249560
F: Allocated instance id 1628789924
F: Xdg dir xdg-videos is $HOME (i.e. disabled), ignoring
F: Xdg dir xdg-desktop is $HOME (i.e. disabled), ignoring
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/nikos/.config/pulse/client.conf': Error opening file /home/nikos/.config/pulse/client.conf: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
F: Running 'bwrap --args 32 /usr/libexec/flatpak-dbus-proxy --args=34'
F: Running 'bwrap --args 29 viber'
sh: xdg-mime: εντολή δεν βρέθηκε
Qt WebEngine ICU data not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine resources not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine ICU data not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine resources not found at /app/extra/viber/resources. Trying parent directory...
qml: type=""
failed to register service "org.kde.StatusNotifierItem-3-2"
qml: type=""

**Comment by nickkefi** [comment]
The Greek sentences are "no such file or directory" and "command not found"

**Comment by ivonenchev** [comment]
I have the same issue. But I have different outputs from nickkefis' outputs.

Does anyone have any idea about this blank page issue?

**Comment by ivonenchev** [comment]
After reinstalling my operation system OpenSuse Tumbleweed, Viber is working as usual.

**Comment by nickkefi** [comment]
The issue is gone after deleting ~/.var/app/com.viber.Viber

**Comment by vukasin-nikodijevic** [comment]
Solution: https://github.com/flathub/com.viber.Viber/issues/9#issuecomment-455344537 

My current setup: Debian GNU/Linux 9.6 (stretch) 64-bit - stable

**Comment by 0xAF** [comment]
> The issue is gone after deleting ~/.var/app/com.viber.Viber

Removing the `~/.var/app/com.viber.Viber/cache` folder is enough.

**Comment by stavpup** [comment]
~ >>> flatpak info com.viber.Viber

Viber - We connect people, no matter who they are or where they are from.

          ID: com.viber.Viber
         Ref: app/com.viber.Viber/x86_64/stable
        Arch: x86_64
      Branch: stable
     License: LicenseRef-proprietary
      Origin: flathub
      
      
  Collection: org.flathub.Stable
Installation: system
   Installed: 40,3 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: 7645126cc6fdba546d16d6d8b548d20d1b25a6f5e73e95d9fe7e278940a961e3
      Parent: 0580aa5896873c18820ce4958c8ba98dfae47dbd949ff9d98f7cf0f3723629d2
     Subject: Switch to stable runtime version 18.08 (79dccabe)
        Date: 2018-08-20 20:26:47 +0000
~ >>>

flatpak -v run com.viber.Viber                                        [1]
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/stavros/.local/share/flatpak
F: Opening user flatpak installation at path /home/stavros/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/stavros/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2806119497
F: Allocated instance id 391731454
F: Add defaults in dir /com/viber/Viber/
F: Add locks in dir /com/viber/Viber/
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/stavros/.config/pulse/client.conf': Error opening file /home/stavros/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 35 xdg-dbus-proxy --args=37'
F: Running 'bwrap --args 35 viber'
Qt: Session management error: None of the authentication protocols specified are supported
sh: xdg-mime: command not found
Qt WebEngine ICU data not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine resources not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine ICU data not found at /app/extra/viber/resources. Trying parent directory...
Qt WebEngine resources not found at /app/extra/viber/resources. Trying parent directory...
QQuickItem: Cannot set activeFocusOnTab to false once item is the active focus item.

**Comment by stavpup** [comment]
Deleting com.viber.Viber and ~/.var/app/com.viber.Viber/cache did nothing.

**Comment by bioname** [comment]
sometimes this happens again. so...
Just try to clear ~/.cache/qtshadercache folder ;)

**Comment by akurtakov** [comment]
Do you still see the issue after latest updates?

**Comment by ivonenchev** [comment]
I don't have any simillar issue.  Thank you, you can close the SR.
