### ISSUE TITLE
Some messages are displaying on the phone but not in the desktop app.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [flathub/com.viber.Viber#91]
I've received an important message and I wanted to read it from desktop app but it's not displayed there. It's inside a folder "Business chats" and none of those are displayed in the desktop app for some reason. I've even found and exact channel manually but its messages are different on my phone and desktop and not synced at all. My phone number is the same for sure in both apps and both are working since I'm chatting with people both on the phone and desktop.
Android 7, Windows 11. Viber apps are both up to date at the moment.

**Comment by SmallAndSoft** [comment]
I can confrm that Flatpack Viber does not show Business Chat messages sent for me. My messages to Business Chat account are shown alright though.

**Comment by akurtakov** [comment]
This doesn't sound as packaging issue to me but more like a bug in Viber for linux.

**Comment by SmallAndSoft** [comment]
> This doesn't sound as packaging issue to me but more like a bug in Viber for linux.

Possibly. Still worth reporting for Flatpack version.

**Comment by iG8R** [comment]
I have the same issue as described in the first post.

**Comment by fx-practic** [comment]
Me too, Windows 10.

**Comment by akurtakov** [comment]
AFAIK there is no way to run flatpaks on windows so definetely upstream problem. It is not clear to me how exactly to report the issue to https://www.viber.com/en/ but there is nothing to be done in the flatpak as it uses the prebuild binary.
